name: Cross-platform Build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string
        default: 'v1.0.0'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            build_script: npm run build:linux && npm run build:linux-appimage
            artifacts: |
              src-tauri/target/release/*.deb
              src-tauri/target/release/*.AppImage
          - os: macos-11
            build_script: npm run build:macos
            artifacts: src-tauri/target/release/*.dmg
          - os: windows-2019
            build_script: npm run build:win32 && npm run build:win32-portable
            artifacts: |
              src-tauri/target/release/*.exe
              src-tauri/target/release/*-portable.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: ${{ matrix.build_script }}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifacts }}
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

